package com.marketplace.MarketBack.exception.enums;

public enum ErrorCode {
    USER_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    INVALID_CREDENTIALS,
    TRADE_NOT_FOUND, PRODUCT_NOT_FOUND, VALIDATION_ERROR,
    SALE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    PRODUCT_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    INVALID_ROLE,
    INVALID_TOKEN,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    CONVERSATION_NOT_FOUND,

}
